from django.urls import path
from .views import (
    ExamListCreateView, ExamDetailView,
    ExamScheduleListCreateView, ExamScheduleDetailView,
    MarkListCreateView, MarkDetailView,
    StudentReportCardView,
    QuestionBankListCreateView, QuestionBankDetailView,
    OnlineExamListCreateView, OnlineExamDetailView,
    OnlineExamQuestionListCreateView, OnlineExamQuestionDetailView,
    ExamAttemptListCreateView, ExamAttemptDetailView,
    ExamAnswerListCreateView, ExamAnswerDetailView,
    HallTicketListCreateView, HallTicketDetailView,
    ResultListCreateView, ResultDetailView,
    ReportCardListCreateView, ReportCardDetailView,
    OMREvaluationListCreateView, OMREvaluationDetailView,
    CertificateListCreateView, CertificateDetailView,
)

urlpatterns = [
    path('', ExamListCreateView.as_view(), name='exam_list_create'),
    path('<uuid:pk>/', ExamDetailView.as_view(), name='exam_detail'),
    path('schedules/', ExamScheduleListCreateView.as_view(), name='exam_schedule_list_create'),
    path('schedules/<uuid:pk>/', ExamScheduleDetailView.as_view(), name='exam_schedule_detail'),
    path('marks/', MarkListCreateView.as_view(), name='marks_list_create'),
    path('marks/<uuid:pk>/', MarkDetailView.as_view(), name='marks_detail'),
    path('report-card/<uuid:student_id>/', StudentReportCardView.as_view(), name='student_report_card'),

    path('question-bank/', QuestionBankListCreateView.as_view(), name='question_bank_list_create'),
    path('question-bank/<uuid:pk>/', QuestionBankDetailView.as_view(), name='question_bank_detail'),
    path('online-exams/', OnlineExamListCreateView.as_view(), name='online_exam_list_create'),
    path('online-exams/<uuid:pk>/', OnlineExamDetailView.as_view(), name='online_exam_detail'),
    path('online-exam-questions/', OnlineExamQuestionListCreateView.as_view(), name='online_exam_question_list_create'),
    path('online-exam-questions/<uuid:pk>/', OnlineExamQuestionDetailView.as_view(), name='online_exam_question_detail'),
    path('attempts/', ExamAttemptListCreateView.as_view(), name='exam_attempt_list_create'),
    path('attempts/<uuid:pk>/', ExamAttemptDetailView.as_view(), name='exam_attempt_detail'),
    path('answers/', ExamAnswerListCreateView.as_view(), name='exam_answer_list_create'),
    path('answers/<uuid:pk>/', ExamAnswerDetailView.as_view(), name='exam_answer_detail'),
    path('hall-tickets/', HallTicketListCreateView.as_view(), name='hall_ticket_list_create'),
    path('hall-tickets/<uuid:pk>/', HallTicketDetailView.as_view(), name='hall_ticket_detail'),
    path('results/', ResultListCreateView.as_view(), name='result_list_create'),
    path('results/<uuid:pk>/', ResultDetailView.as_view(), name='result_detail'),
    path('report-cards/', ReportCardListCreateView.as_view(), name='report_card_list_create'),
    path('report-cards/<uuid:pk>/', ReportCardDetailView.as_view(), name='report_card_detail'),
    path('omr-evaluations/', OMREvaluationListCreateView.as_view(), name='omr_evaluation_list_create'),
    path('omr-evaluations/<uuid:pk>/', OMREvaluationDetailView.as_view(), name='omr_evaluation_detail'),
    path('certificates/', CertificateListCreateView.as_view(), name='certificate_list_create'),
    path('certificates/<uuid:pk>/', CertificateDetailView.as_view(), name='certificate_detail'),
]
