from django.urls import path
from .views import (
    CMSPageListCreateView, CMSPageDetailView,
    CMSSectionListCreateView, CMSSectionDetailView,
    NewsListCreateView, NewsDetailView,
    EventListCreateView, EventDetailView,
    GalleryListCreateView, GalleryDetailView,
    FAQListCreateView, FAQDetailView,
    DownloadListCreateView, DownloadDetailView,
    AchievementListCreateView, AchievementDetailView,
    TestimonialListCreateView, TestimonialDetailView,
    FacilityListCreateView, FacilityDetailView,
    CareerPostListCreateView, CareerPostDetailView,
    CareerApplicationListCreateView, CareerApplicationDetailView,
    ContactInquiryListCreateView, ContactInquiryDetailView,
)

urlpatterns = [
    path('pages/', CMSPageListCreateView.as_view(), name='cms_page_list_create'),
    path('pages/<uuid:pk>/', CMSPageDetailView.as_view(), name='cms_page_detail'),
    path('sections/', CMSSectionListCreateView.as_view(), name='cms_section_list_create'),
    path('sections/<uuid:pk>/', CMSSectionDetailView.as_view(), name='cms_section_detail'),
    path('news/', NewsListCreateView.as_view(), name='news_list_create'),
    path('news/<uuid:pk>/', NewsDetailView.as_view(), name='news_detail'),
    path('events/', EventListCreateView.as_view(), name='event_list_create'),
    path('events/<uuid:pk>/', EventDetailView.as_view(), name='event_detail'),
    path('gallery/', GalleryListCreateView.as_view(), name='gallery_list_create'),
    path('gallery/<uuid:pk>/', GalleryDetailView.as_view(), name='gallery_detail'),
    path('faqs/', FAQListCreateView.as_view(), name='faq_list_create'),
    path('faqs/<uuid:pk>/', FAQDetailView.as_view(), name='faq_detail'),
    path('downloads/', DownloadListCreateView.as_view(), name='download_list_create'),
    path('downloads/<uuid:pk>/', DownloadDetailView.as_view(), name='download_detail'),
    path('achievements/', AchievementListCreateView.as_view(), name='achievement_list_create'),
    path('achievements/<uuid:pk>/', AchievementDetailView.as_view(), name='achievement_detail'),
    path('testimonials/', TestimonialListCreateView.as_view(), name='testimonial_list_create'),
    path('testimonials/<uuid:pk>/', TestimonialDetailView.as_view(), name='testimonial_detail'),
    path('facilities/', FacilityListCreateView.as_view(), name='facility_list_create'),
    path('facilities/<uuid:pk>/', FacilityDetailView.as_view(), name='facility_detail'),
    path('careers/', CareerPostListCreateView.as_view(), name='career_post_list_create'),
    path('careers/<uuid:pk>/', CareerPostDetailView.as_view(), name='career_post_detail'),
    path('career-applications/', CareerApplicationListCreateView.as_view(), name='career_application_list_create'),
    path('career-applications/<uuid:pk>/', CareerApplicationDetailView.as_view(), name='career_application_detail'),
    path('contact-inquiries/', ContactInquiryListCreateView.as_view(), name='contact_inquiry_list_create'),
    path('contact-inquiries/<uuid:pk>/', ContactInquiryDetailView.as_view(), name='contact_inquiry_detail'),
]
