from django.urls import path
from .views import (
    CourseListCreateView, CourseDetailView,
    LessonListCreateView, LessonDetailView,
    AssignmentListCreateView, AssignmentDetailView,
    SubmissionListCreateView, SubmissionDetailView, SubmissionGradeView,
    EnrollmentListCreateView, EnrollmentDetailView,
    ProgressListCreateView, ProgressDetailView,
    OnlineClassListCreateView, OnlineClassDetailView,
    QuizListCreateView, QuizDetailView,
    QuizQuestionListCreateView, QuizQuestionDetailView,
    QuizAttemptListCreateView, QuizAttemptDetailView,
    ForumTopicListCreateView, ForumTopicDetailView,
    ForumPostListCreateView, ForumPostDetailView,
    AITutorSessionListCreateView, AITutorSessionDetailView,
)

urlpatterns = [
    path('courses/', CourseListCreateView.as_view(), name='course_list_create'),
    path('courses/<uuid:pk>/', CourseDetailView.as_view(), name='course_detail'),
    path('lessons/', LessonListCreateView.as_view(), name='lesson_list_create'),
    path('lessons/<uuid:pk>/', LessonDetailView.as_view(), name='lesson_detail'),
    path('assignments/', AssignmentListCreateView.as_view(), name='assignment_list_create'),
    path('assignments/<uuid:pk>/', AssignmentDetailView.as_view(), name='assignment_detail'),
    path('submissions/', SubmissionListCreateView.as_view(), name='submission_list_create'),
    path('submissions/<uuid:pk>/', SubmissionDetailView.as_view(), name='submission_detail'),
    path('submissions/<uuid:pk>/grade/', SubmissionGradeView.as_view(), name='submission_grade'),

    path('enrollments/', EnrollmentListCreateView.as_view(), name='lms_enrollment_list_create'),
    path('enrollments/<uuid:pk>/', EnrollmentDetailView.as_view(), name='lms_enrollment_detail'),
    path('progress/', ProgressListCreateView.as_view(), name='lms_progress_list_create'),
    path('progress/<uuid:pk>/', ProgressDetailView.as_view(), name='lms_progress_detail'),
    path('online-classes/', OnlineClassListCreateView.as_view(), name='online_class_list_create'),
    path('online-classes/<uuid:pk>/', OnlineClassDetailView.as_view(), name='online_class_detail'),
    path('quizzes/', QuizListCreateView.as_view(), name='quiz_list_create'),
    path('quizzes/<uuid:pk>/', QuizDetailView.as_view(), name='quiz_detail'),
    path('quiz-questions/', QuizQuestionListCreateView.as_view(), name='quiz_question_list_create'),
    path('quiz-questions/<uuid:pk>/', QuizQuestionDetailView.as_view(), name='quiz_question_detail'),
    path('quiz-attempts/', QuizAttemptListCreateView.as_view(), name='quiz_attempt_list_create'),
    path('quiz-attempts/<uuid:pk>/', QuizAttemptDetailView.as_view(), name='quiz_attempt_detail'),
    path('forum-topics/', ForumTopicListCreateView.as_view(), name='forum_topic_list_create'),
    path('forum-topics/<uuid:pk>/', ForumTopicDetailView.as_view(), name='forum_topic_detail'),
    path('forum-posts/', ForumPostListCreateView.as_view(), name='forum_post_list_create'),
    path('forum-posts/<uuid:pk>/', ForumPostDetailView.as_view(), name='forum_post_detail'),
    path('ai-tutor-sessions/', AITutorSessionListCreateView.as_view(), name='ai_tutor_session_list_create'),
    path('ai-tutor-sessions/<uuid:pk>/', AITutorSessionDetailView.as_view(), name='ai_tutor_session_detail'),
]
