# Generated by Django 4.2.30 on 2026-07-07 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=80, null=True)),
                ('state', models.CharField(blank=True, max_length=80, null=True)),
                ('country', models.CharField(default='India', max_length=80)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_headquarters', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'campuses',
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(default='EduNova Global Academy Private Limited', max_length=200)),
                ('brand_name', models.CharField(blank=True, max_length=200, null=True)),
                ('tagline', models.CharField(blank=True, default='Inspiring Minds. Building Futures.', max_length=255, null=True)),
                ('website_domain', models.CharField(blank=True, max_length=255, null=True)),
                ('industry', models.JSONField(blank=True, default=list)),
                ('company_type', models.CharField(blank=True, max_length=120, null=True)),
                ('established_year', models.IntegerField(blank=True, null=True)),
                ('headquarters', models.TextField(blank=True, null=True)),
                ('student_strength', models.IntegerField(blank=True, null=True)),
                ('staff_strength', models.IntegerField(blank=True, null=True)),
                ('vision', models.TextField(blank=True, null=True)),
                ('mission', models.TextField(blank=True, null=True)),
                ('core_values', models.JSONField(blank=True, default=list)),
                ('color_palette', models.JSONField(blank=True, default=dict)),
                ('typography', models.JSONField(blank=True, default=dict)),
                ('logo_concept', models.TextField(blank=True, null=True)),
                ('brand_personality', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'company_profile',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('department_type', models.CharField(choices=[('Academic', 'Academic'), ('Administration', 'Administration'), ('Finance', 'Finance'), ('Accounts', 'Accounts'), ('Human Resources', 'Human Resources'), ('IT', 'IT'), ('Examination', 'Examination'), ('Sports', 'Sports'), ('Hostel', 'Hostel'), ('Medical', 'Medical'), ('Research', 'Research'), ('Innovation', 'Innovation'), ('Library', 'Library'), ('Transport', 'Transport'), ('Other', 'Other')], default='Academic', max_length=60)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='tenants.campus')),
                ('head_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_headed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
    ]
