# Generated by Django 4.2.30 on 2026-07-04 07:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'guardians',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('admission_no', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('Enrolled', 'Enrolled'), ('Withdrawn', 'Withdrawn'), ('Alumni', 'Alumni')], default='Enrolled', max_length=20)),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='StudentGuardianMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('relationship_type', models.CharField(default='Father', max_length=50)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.guardian')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'db_table': 'student_guardian_mappings',
                'unique_together': {('student', 'guardian')},
            },
        ),
        migrations.AddField(
            model_name='student',
            name='guardians',
            field=models.ManyToManyField(related_name='students', through='students.StudentGuardianMapping', to='students.guardian'),
        ),
    ]
